# Generated by Django 2.2.4 on 2019-10-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
