# Generated by Django 2.2.4 on 2019-10-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191021_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='user',
        ),
    ]
